
version: "3.8"
services:
  postgres-57348:
    image: postgres:13
    environment:
      POSTGRES_USER: notesadmin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notesapi
    ports:
      - '57348:5432'
    volumes:
      - ./scripts/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - db-57348:/var/lib/postgresql/data

  vteachers-app-49157:
    build:
      context: .
    depends_on:
      - postgres-57348
    ports:
      - '49157:4000'
    environment:
      DB_HOST: postgres-57348
      PORT: 4000
      HOST: localhost
    volumes:
      - ./vteachers:/opt/vteachers-app/vteachers
      - ./public:/opt/vteachers-app/public
      - ./scripts:/opt/vteachers-app/scripts
      - ./server:/opt/vteachers-app/server
      - ./src:/opt/vteachers-app/src
      - ./credentials.js:/opt/vteachers-app/credentials.js

volumes:
  db-57348:
